# 1. Configuracion de la Conexion (JDBC)
spring.datasource.url=jdbc:mysql://localhost:3306/segundumProductos?serverTimezone=CET
spring.datasource.username=usuario_productos
spring.datasource.password=productos2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Configuracion de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola (no logback, no estan afectadas por los niveles de log)
	# mostrar las consultas SQL
spring.jpa.show-sql=false
	# formatear las consultas SQL para que sean mas legibles
spring.jpa.properties.hibernate.format_sql=true

# 3. Niveles de Log
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR

# 4. Path matching (Spring Boot 2.6+ usa PathPatternParser por defecto, Ant es mas compatible)
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Documentación de la api
springdoc.api-docs.path=/api-docs
# Indica que los paths generados deben ignorar el prefijo /api que tienen los controladores
springdoc.api-docs.groups.enabled=true
springdoc.paths-to-match=/api/**
# Este ajuste es para que al mostrarse en Swagger se vea sin el /api
springdoc.api-docs.resolve-schema-properties=true

# Recursos api
## estas variables quedan deprecadas en produccion (en OCI)
api.url.gateway = ${API_URL_GATEWAY:http://localhost:8090}
api.url.base = http://localhost:8080
api.url.swaggerui = ${api.url.base}/swagger-ui.html

# RabbitMQ (CloudAMQP)
spring.rabbitmq.host=rat.rmq2.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=cfrvyzor
spring.rabbitmq.password=Y2mLAqiR1mOFZBBnupB6UDZ6o9E778iX
spring.rabbitmq.virtual-host=cfrvyzor
spring.rabbitmq.ssl.enabled=true

# Permitir que la documentacion se sirva correctamente a traves del Gateway (pasarela zuul)
server.forward-headers-strategy=none
