# github oauth2
spring.security.oauth2.client.registration.github.clientId=${PASARELA_GITHUB_ID:Ov23liDl16imSLDg5EP3}
spring.security.oauth2.client.registration.github.clientSecret=${PASARELA_GITHUB_SECRET:4d402dc3a5f5ca4c5adfe8c54b60e4fdc0db7993}
spring.security.oauth2.client.registration.github.redirect-uri=${PASARELA_GITHUB_REDIRECT:http://localhost:8090/login/oauth2/code/github}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# netflix zuul endpoints
server.port = 8090
spring.application.name = pasarela
zuul.sensitiveHeaders=
zuul.routes.productos.path = /productos/**
zuul.routes.productos.url = http://localhost:8080/api/productos
zuul.routes.categorias.path = /categorias/**
zuul.routes.categorias.url = http://localhost:8080/api/categorias
zuul.routes.usuarios.path = /usuarios/**
zuul.routes.usuarios.url = http://localhost:8081/api/usuarios
zuul.routes.compraventas.path = /compraventas/**
zuul.routes.compraventas.url = http://localhost:8082/api/compraventas

# netflix zuul endpoints docs
zuul.routes.docs-productos.path = /docs/productos/**
zuul.routes.docs-productos.url = http://localhost:8080/api-docs
zuul.routes.docs-usuarios.path = /docs/usuarios/**
zuul.routes.docs-usuarios.url = http://localhost:8081/api-docs
zuul.routes.docs-compraventas.path = /docs/compraventas/**
zuul.routes.docs-compraventas.url = http://localhost:8082/api-docs

# Configuracion del agregador de Swagger en la Pasarela
springdoc.swagger-ui.urls[0].name=Productos
springdoc.swagger-ui.urls[0].url=/docs/productos
springdoc.swagger-ui.urls[1].name=Usuarios
springdoc.swagger-ui.urls[1].url=/docs/usuarios
springdoc.swagger-ui.urls[2].name=Compraventas
springdoc.swagger-ui.urls[2].url=/docs/compraventas
springdoc.swagger-ui.urls[3].name=Auntenticacion
springdoc.swagger-ui.urls[3].url=/api-docs

# Documentacion de la api
springdoc.api-docs.path=/api-docs